server:
  port: 7090
  servlet:
    context-path: /auth-service

jwt:
  auth:
    converter:
      resource-id: authenticationClientId

keycloak:
  realm: aymeric-music
  domain: keycloak.codewithaymeric.com
  adminClientId: admin-cli
  adminClientSecret: 4c0e1b2d-3f8a-4f5b-9a7c-6d0e1b2d3f8a
  client: authenticationClientId
  uris:
    auth: https://${keycloak.domain}
spring:
  profile:
    active: prod
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${keycloak.domain}/realms/${keycloak.realm}
