server:
  port: 7090
  servlet:
    context-path: /auth-service
      # Add this to prevent file downloads
    register-default-servlet: false

jwt:
  auth:
    converter:
      resource-id: authenticationClientId

keycloak:
  realm: aymeric-music
  domain: http://localhost:8080 #keycloak.codewithaymeric.com
  adminClientId: admin-cli
  adminClientSecret: cWrHX7e3PM9oAmaUniuHHyabJxtiKPHV
  client: authenticationClientId
  uris:
    auth: http://localhost:8080 #https://${keycloak.domain}
spring:
  profile:
    active: prod
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/aymeric-music

